# Generated by Django 4.1 on 2022-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('desc', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
